import inquirer from 'inquirer';
async function askQuestion() {
    console.log("Welcome Number to Guessing Game!");
    const numbertoguess = Math.floor(Math.random() * 10) + 1;
    //console.log(`The Random Number generated by computer between 1 and 10 is ${numbertoguess}`)
    let round = 0;
    do {
        const questions = [
            {
                type: "number",
                name: "ask",
                message: "Enter your guessed number!",
                validate: async (ask) => {
                    if (isNaN(ask)) {
                        return "Please enter valid number!";
                    }
                    return true;
                },
            },
        ];
        await inquirer
            .prompt(questions)
            .then((answers) => {
            // Use user feedback for... whatever!!
            round += 1;
            console.log(`Round: ${round}`);
            if (answers.ask > numbertoguess) {
                console.log(`Opps! Incorrect, your guessed number is greater then the random number!`);
            }
            else if (answers.ask < numbertoguess) {
                console.log(`Opps! Incorrect, your guessed number is lesser then the random number!`);
            }
            else {
                console.log(`Congratulations! your guess was correct. The random number is indeed ${numbertoguess}`);
                return round = 3;
            }
        });
    } while (round < 3);
}
async function startagain() {
    var again;
    do {
        await askQuestion();
        again = await inquirer
            .prompt({
            type: "input",
            name: "restart",
            message: "Do you want to continue?",
            default: "(Y or N)"
        });
    } while (again.restart == 'y' || again.restart == 'Y');
}
startagain();
